# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb443ae40456a66fd0d15396eb47ce4821b06f5a082641c647eacd04298880cc35eb1d01e685619aa71de22a703746c82e35a870f6ccc062bcbe4851d3946e1b

test:
  secret_key_base: f55d60d76e110d14cbf2820c89e15019639594f5add82e5a6a03f55e2d0558bd14ed7ffddf24445e1f670fe62095431db29aacfeaa99abe7ea0b3eb2a834b946

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
